import type { Metadata, Viewport } from "next";
import { Archivo } from "next/font/google";
import SideRail from "@/components/SideRail";
import SiteHeader from "@/components/SiteHeader";
import MobileTabBar from "@/components/MobileTabBar";
import LanguageProvider from "@/components/i18n/LanguageProvider";
import PersonalizationProvider from "@/components/personalization/PersonalizationProvider";
import ThemeProvider from "@/components/theme/ThemeProvider";
import CustomCursor from "@/components/motion/CustomCursor";
import GlassLight from "@/components/motion/GlassLight";
import BackToTop from "@/components/motion/BackToTop";
import PwaRegister from "@/components/PwaRegister";
import OfflineChip from "@/components/OfflineChip";
import SkipLink from "@/components/SkipLink";
import WebVitals from "@/components/WebVitals";
import AuthProvider from "@/components/auth/AuthProvider";
import TripProvider from "@/components/trip/TripProvider";
import SeasonalReminderProvider from "@/components/seasonal/SeasonalReminderProvider";
import CommandPalette from "@/components/command/CommandPalette";
import KeyboardShortcuts from "@/components/command/KeyboardShortcuts";
import ViewTransitions from "@/components/transitions/ViewTransitions";
import ToastProvider from "@/components/ui/ToastProvider";
import "./globals.css";

// Set the theme class before paint to avoid a flash of the wrong theme, and
// the force-motion class (the user's "always animate" override of the OS
// reduced-motion setting — see lib/motion.ts) so animations don't flash-freeze.
const themeScript = `(function(){try{var t=localStorage.getItem("farms.theme");if(t==="dark"||(!t&&window.matchMedia("(prefers-color-scheme: dark)").matches)){document.documentElement.classList.add("dark")}if(localStorage.getItem("farms.motion")==="on"){document.documentElement.classList.add("force-motion")}}catch(e){}})();`;

const archivo = Archivo({
  subsets: ["latin"],
  variable: "--font-archivo",
});

export const metadata: Metadata = {
  // Resolves relative canonical/Open-Graph URLs (e.g. on /farm/[id]) to absolute
  // ones. Set NEXT_PUBLIC_SITE_URL in production; localhost is the dev fallback.
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000",
  ),
  description:
    "Fresh products, direct from Swiss farms — find what you need at the farm nearest to you.",
  // iOS Safari auto-links things that look like phone numbers / addresses /
  // dates (the directory is full of coordinates, postal codes and counts),
  // injecting <a> tags into the SSR DOM *before* React hydrates → a hydration
  // mismatch that only shows on iPhone (desktop Safari doesn't do this). Turn
  // the detection off so the markup React hydrates is the markup it rendered.
  formatDetection: {
    telephone: false,
    date: false,
    address: false,
    email: false,
  },
  icons: {
    // favicon.ico is served by app/favicon.ico; the scalable mark covers every
    // other size. The Apple touch icon is generated by app/apple-icon.tsx.
    icon: [
      { sizes: "any", url: "/favicon.ico" },
      { type: "image/svg+xml", url: "/icon.svg" },
    ],
    shortcut: "/favicon.ico",
  },
  title: {
    default: "Swiss farms",
    template: "%s | farms",
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "farms",
  },
};

export const viewport: Viewport = {
  // Tint the browser chrome to match the page surface so the UI feels
  // immersive — and so dark mode doesn't show a green bar over a dark page.
  // (The installed-PWA brand colour stays green via app/manifest.ts.)
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#f4f4ef" },
    { media: "(prefers-color-scheme: dark)", color: "#0e0f12" },
  ],
  // maximum-scale=1 disables iOS Safari's AUTOMATIC zooms (input focus zoom,
  // double-tap zoom) that left the page stuck zoomed-in and shifted sideways.
  // iOS deliberately ignores the cap for the user's own pinch gesture, so
  // accessibility zoom still works.
  maximumScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={archivo.variable}>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
        <ThemeProvider>
          <LanguageProvider>
            <ViewTransitions>
              <ToastProvider>
                <AuthProvider>
                  <PersonalizationProvider>
                    <TripProvider>
                      <SeasonalReminderProvider>
                        <SkipLink />
                        <SideRail />
                        <div className="cursor-zone relative z-[1] pb-[calc(6rem+env(safe-area-inset-bottom))] lg:pb-0 lg:pl-[76px]">
                          <SiteHeader />
                          <div id="main-content">{children}</div>
                        </div>
                        <MobileTabBar />
                        <CommandPalette />
                        <KeyboardShortcuts />
                        <CustomCursor />
                        <GlassLight />
                        <BackToTop />
                        <PwaRegister />
                        <OfflineChip />
                        <WebVitals />
                      </SeasonalReminderProvider>
                    </TripProvider>
                  </PersonalizationProvider>
                </AuthProvider>
              </ToastProvider>
            </ViewTransitions>
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
