import type { Metadata, Viewport } from "next";
import { Archivo } from "next/font/google";
import SideRail from "@/components/SideRail";
import SiteHeader from "@/components/SiteHeader";
import MobileTabBar from "@/components/MobileTabBar";
import LanguageProvider from "@/components/i18n/LanguageProvider";
import PersonalizationProvider from "@/components/personalization/PersonalizationProvider";
import ThemeProvider from "@/components/theme/ThemeProvider";
import CustomCursor from "@/components/motion/CustomCursor";
import GlassLight from "@/components/motion/GlassLight";
import AmbientBackdrop from "@/components/hero/AmbientBackdrop";
import MotionPrompt from "@/components/motion/MotionPrompt";
import BackToTop from "@/components/motion/BackToTop";
import PwaRegister from "@/components/PwaRegister";
import OfflineChip from "@/components/OfflineChip";
import SkipLink from "@/components/SkipLink";
import WebVitals from "@/components/WebVitals";
import AuthProvider from "@/components/auth/AuthProvider";
import TripProvider from "@/components/trip/TripProvider";
import SeasonalReminderProvider from "@/components/seasonal/SeasonalReminderProvider";
import CommandPalette from "@/components/command/CommandPalette";
import KeyboardShortcuts from "@/components/command/KeyboardShortcuts";
import ViewTransitions from "@/components/transitions/ViewTransitions";
import ToastProvider from "@/components/ui/ToastProvider";
import { LOCALE_CODES, MESSAGES, isLocale, type Locale } from "@/lib/i18n";
import "../globals.css";

// Set the theme class before paint to avoid a flash of the wrong theme, and
// the force-motion class (the user's "always animate" override of the OS
// reduced-motion setting — see lib/motion.ts) so animations don't flash-freeze.
// Applies the theme before paint. Modes: light/dark are explicit; system asks
// the media query; sun replays the LAST RESOLVED theme ("farms.theme", kept
// fresh by ThemeProvider) and the provider re-resolves right after mount --
// worst case is a brief stale theme after a sunrise/sunset passed while away,
// never a flash.
const themeScript = `(function(){try{var m=localStorage.getItem("farms.themeMode");var t=localStorage.getItem("farms.theme");var dark;if(m==="dark"){dark=true}else if(m==="light"){dark=false}else if(m==="system"){dark=window.matchMedia("(prefers-color-scheme: dark)").matches}else if(m==="sun"){dark=t==="dark"}else{dark=t==="dark"||(!t&&window.matchMedia("(prefers-color-scheme: dark)").matches)}if(dark){document.documentElement.classList.add("dark")}if(localStorage.getItem("farms.motion")==="on"){document.documentElement.classList.add("force-motion")}}catch(e){}})();`;

const archivo = Archivo({
  subsets: ["latin"],
  variable: "--font-archivo",
});

export const metadata: Metadata = {
  // Resolves relative canonical/Open-Graph URLs (e.g. on /farm/[id]) to absolute
  // ones. Set NEXT_PUBLIC_SITE_URL in production; localhost is the dev fallback.
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000",
  ),
  description:
    "Fresh products, direct from Swiss farms — find what you need at the farm nearest to you.",
  // iOS Safari auto-links things that look like phone numbers / addresses /
  // dates (the directory is full of coordinates, postal codes and counts),
  // injecting <a> tags into the SSR DOM *before* React hydrates → a hydration
  // mismatch that only shows on iPhone (desktop Safari doesn't do this). Turn
  // the detection off so the markup React hydrates is the markup it rendered.
  formatDetection: {
    telephone: false,
    date: false,
    address: false,
    email: false,
  },
  icons: {
    // favicon.ico is served by app/favicon.ico; the scalable mark covers every
    // other size. The Apple touch icon is generated by app/apple-icon.tsx.
    icon: [
      { sizes: "any", url: "/favicon.ico" },
      { type: "image/svg+xml", url: "/icon.svg" },
    ],
    shortcut: "/favicon.ico",
  },
  title: {
    default: "farms.",
    template: "%s | farms",
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "farms",
    // iOS launch screens — without these the installed app cold-launches to a
    // white flash. iOS picks by EXACT device match, hence one image per
    // device class (regenerate with: node scripts/generate-splash.mjs).
    startupImage: [
      {
        url: "/splash/750x1334.png",
        media:
          "(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
      },
      {
        url: "/splash/1170x2532.png",
        media:
          "(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      {
        url: "/splash/1179x2556.png",
        media:
          "(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      {
        url: "/splash/1206x2622.png",
        media:
          "(device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      {
        url: "/splash/1242x2688.png",
        media:
          "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      {
        url: "/splash/1284x2778.png",
        media:
          "(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      {
        url: "/splash/1290x2796.png",
        media:
          "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      {
        url: "/splash/1320x2868.png",
        media:
          "(device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      {
        url: "/splash/828x1792.png",
        media:
          "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
      },
      {
        url: "/splash/1125x2436.png",
        media:
          "(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      {
        url: "/splash/1620x2160.png",
        media:
          "(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
      },
      {
        url: "/splash/1640x2360.png",
        media:
          "(device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
      },
      {
        url: "/splash/1668x2388.png",
        media:
          "(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
      },
      {
        url: "/splash/2048x2732.png",
        media:
          "(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
      },
    ],
  },
};

export const viewport: Viewport = {
  // Tint the browser chrome to match the page surface so the UI feels
  // immersive — and so dark mode doesn't show a green bar over a dark page.
  // (The installed-PWA brand colour stays green via app/manifest.ts.)
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#f4f4ef" },
    { media: "(prefers-color-scheme: dark)", color: "#0e0f12" },
  ],
  // maximum-scale=1 disables iOS Safari's AUTOMATIC zooms (input focus zoom,
  // double-tap zoom) that left the page stuck zoomed-in and shifted sideways.
  // iOS deliberately ignores the cap for the user's own pinch gesture, so
  // accessibility zoom still works.
  maximumScale: 1,
};

// Pre-render one tree per locale; the middleware rewrites unprefixed URLs to
// /en and passes /de|/fr|/it|/rm straight through.
export function generateStaticParams() {
  return LOCALE_CODES.map((lang) => ({ lang }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}>) {
  const { lang } = await params;
  const locale: Locale = isLocale(lang) ? lang : "en";
  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={archivo.variable}>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
        <ThemeProvider>
          <LanguageProvider initialLocale={locale} messages={MESSAGES[locale]}>
            <ViewTransitions>
              <ToastProvider>
                <AuthProvider>
                  <PersonalizationProvider>
                    <TripProvider>
                      <SeasonalReminderProvider>
                        <SkipLink />
                        <SideRail />
                        <div className="cursor-zone relative z-[1] pb-[calc(6rem+env(safe-area-inset-bottom))] lg:pb-0 lg:pl-[92px]">
                          <SiteHeader />
                          <div id="main-content">{children}</div>
                        </div>
                        <MobileTabBar />
                        <CommandPalette />
                        <KeyboardShortcuts />
                        <CustomCursor />
                        <GlassLight />
                        <AmbientBackdrop />
                        <MotionPrompt />
                        <BackToTop />
                        <PwaRegister />
                        <OfflineChip />
                        <WebVitals />
                      </SeasonalReminderProvider>
                    </TripProvider>
                  </PersonalizationProvider>
                </AuthProvider>
              </ToastProvider>
            </ViewTransitions>
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
