import { Suspense } from "react";
import { lang as rootLang } from "next/root-params";
import type { Metadata, Viewport } from "next";
import { Archivo } from "next/font/google";
import BackToTop from "@/components/motion/BackToTop";
import MotionPrompt from "@/components/motion/MotionPrompt";
import DeferredChrome from "@/components/DeferredChrome";
import SideRail from "@/components/SideRail";
import SiteHeader from "@/components/SiteHeader";
import MobileTabBar from "@/components/MobileTabBar";
import LanguageProvider from "@/components/i18n/LanguageProvider";
import PersonalizationProvider from "@/components/personalization/PersonalizationProvider";
import ThemeProvider from "@/components/theme/ThemeProvider";
import CustomCursor from "@/components/motion/CustomCursor";
import LazyAmbientBackdrop from "@/components/hero/LazyAmbientBackdrop";
import SkipLink from "@/components/SkipLink";
import AuthProvider from "@/components/auth/AuthProvider";
import TripProvider from "@/components/trip/TripProvider";
import SeasonalReminderProvider from "@/components/seasonal/SeasonalReminderProvider";
import LazyCommandPalette from "@/components/command/LazyCommandPalette";
import ViewTransitions from "@/components/transitions/ViewTransitions";
import ToastProvider from "@/components/ui/ToastProvider";
import { THEME_SCRIPT } from "@/lib/theme-script";
import { LOCALE_CODES, MESSAGES, isLocale, type Locale } from "@/lib/i18n";
import "../globals.css";

const archivo = Archivo({
  subsets: ["latin"],
  variable: "--font-archivo",
});

export const metadata: Metadata = {
  // Resolves relative canonical/Open-Graph URLs (e.g. on /farm/[id]) to absolute
  // ones. Set NEXT_PUBLIC_SITE_URL in production; localhost is the dev fallback.
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000",
  ),
  description:
    "Fresh products, direct from Swiss farms — find what you need at the farm nearest to you.",
  // iOS Safari auto-links things that look like phone numbers / addresses /
  // dates (the directory is full of coordinates, postal codes and counts),
  // injecting <a> tags into the SSR DOM *before* React hydrates → a hydration
  // mismatch that only shows on iPhone (desktop Safari doesn't do this). Turn
  // the detection off so the markup React hydrates is the markup it rendered.
  formatDetection: {
    telephone: false,
    date: false,
    address: false,
    email: false,
  },
  icons: {
    // favicon.ico is served by app/favicon.ico; the scalable mark covers every
    // other size. The Apple touch icon is generated by app/apple-icon.tsx.
    icon: [
      { sizes: "any", url: "/favicon.ico" },
      { type: "image/svg+xml", url: "/icon.svg" },
    ],
    shortcut: "/favicon.ico",
  },
  title: {
    default: "farms.",
    template: "%s | farms",
  },
  // Next 16 emits the standardized mobile-web-app-capable meta; iOS gates the
  // launch (splash) images on the LEGACY apple-prefixed name, so emit it too.
  other: { "apple-mobile-web-app-capable": "yes" },
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "farms",
    // iOS launch screens — without these the installed app cold-launches to a
    // white flash. iOS picks by EXACT device match; each device gets a dark
    // variant (prefers-color-scheme gated) plus the light fallback
    // (regenerate with: node scripts/generate-splash.mjs).
    startupImage: [
      {
        url: "/splash/750x1334-dark.png",
        media:
          "(prefers-color-scheme: dark) and (device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
      },
      {
        url: "/splash/750x1334-light.png",
        media:
          "(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
      },
      {
        url: "/splash/1170x2532-dark.png",
        media:
          "(prefers-color-scheme: dark) and (device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      {
        url: "/splash/1170x2532-light.png",
        media:
          "(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      {
        url: "/splash/1179x2556-dark.png",
        media:
          "(prefers-color-scheme: dark) and (device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      {
        url: "/splash/1179x2556-light.png",
        media:
          "(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      {
        url: "/splash/1206x2622-dark.png",
        media:
          "(prefers-color-scheme: dark) and (device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      {
        url: "/splash/1206x2622-light.png",
        media:
          "(device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      {
        url: "/splash/1242x2688-dark.png",
        media:
          "(prefers-color-scheme: dark) and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      {
        url: "/splash/1242x2688-light.png",
        media:
          "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      {
        url: "/splash/1260x2736-dark.png",
        media:
          "(prefers-color-scheme: dark) and (device-width: 420px) and (device-height: 912px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      {
        url: "/splash/1260x2736-light.png",
        media:
          "(device-width: 420px) and (device-height: 912px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      {
        url: "/splash/1284x2778-dark.png",
        media:
          "(prefers-color-scheme: dark) and (device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      {
        url: "/splash/1284x2778-light.png",
        media:
          "(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      {
        url: "/splash/1290x2796-dark.png",
        media:
          "(prefers-color-scheme: dark) and (device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      {
        url: "/splash/1290x2796-light.png",
        media:
          "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      {
        url: "/splash/1320x2868-dark.png",
        media:
          "(prefers-color-scheme: dark) and (device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      {
        url: "/splash/1320x2868-light.png",
        media:
          "(device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      {
        url: "/splash/828x1792-dark.png",
        media:
          "(prefers-color-scheme: dark) and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
      },
      {
        url: "/splash/828x1792-light.png",
        media:
          "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
      },
      {
        url: "/splash/1125x2436-dark.png",
        media:
          "(prefers-color-scheme: dark) and (device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      {
        url: "/splash/1125x2436-light.png",
        media:
          "(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      {
        url: "/splash/1620x2160-dark.png",
        media:
          "(prefers-color-scheme: dark) and (device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
      },
      {
        url: "/splash/1620x2160-light.png",
        media:
          "(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
      },
      {
        url: "/splash/1640x2360-dark.png",
        media:
          "(prefers-color-scheme: dark) and (device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
      },
      {
        url: "/splash/1640x2360-light.png",
        media:
          "(device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
      },
      {
        url: "/splash/1668x2388-dark.png",
        media:
          "(prefers-color-scheme: dark) and (device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
      },
      {
        url: "/splash/1668x2388-light.png",
        media:
          "(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
      },
      {
        url: "/splash/2048x2732-dark.png",
        media:
          "(prefers-color-scheme: dark) and (device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
      },
      {
        url: "/splash/2048x2732-light.png",
        media:
          "(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
      },
    ],
  },
};

export const viewport: Viewport = {
  // Tint the browser chrome to match the page surface so the UI feels
  // immersive — and so dark mode doesn't show a green bar over a dark page.
  // (The installed-PWA brand colour stays green via app/manifest.ts.)
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#f4f4ef" },
    { media: "(prefers-color-scheme: dark)", color: "#0e0f12" },
  ],
  // NB: no maximumScale. It used to be capped at 1 to stop iOS Safari's
  // automatic input-focus zoom — but iOS only auto-zooms when a field is
  // smaller than 16px, and that floor is now enforced and asserted by
  // e2e/stress.spec.ts ("form controls meet the 16px iOS no-zoom floor"), so
  // the cap is redundant there. It was NOT harmless elsewhere: Android Chrome
  // honours maximum-scale and was blocking pinch-zoom outright, failing
  // WCAG 1.4.4 (Resize Text) for low-vision users on every route.
};

// Pre-render one tree per locale; the middleware rewrites unprefixed URLs to
// /en and passes /de|/fr|/it|/rm straight through.
export function generateStaticParams() {
  return LOCALE_CODES.map((lang) => ({ lang }));
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // `next/root-params` instead of `await params`. Both give the locale, but
  // only this one is readable while prerendering a route whose DEEPER params
  // are unknown — /farm/[id], the 404 catch-all. Awaiting the layout's own
  // `params` there has nothing to resolve against, which blocked the whole
  // shell and is what stalled the Cache Components migration.
  const lang = await rootLang();
  const locale: Locale = isLocale(lang ?? "") ? (lang as Locale) : "en";
  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={archivo.variable}>
        <script dangerouslySetInnerHTML={{ __html: THEME_SCRIPT }} />
        <ThemeProvider>
          <LanguageProvider initialLocale={locale} messages={MESSAGES[locale]}>
            <ViewTransitions>
              <ToastProvider>
                <AuthProvider>
                  <PersonalizationProvider>
                    <TripProvider>
                      <SeasonalReminderProvider>
                        <SkipLink />
                        <SideRail />
                        <div className="app-shell cursor-zone relative z-[1] pb-[calc(6rem+env(safe-area-inset-bottom))] lg:pb-0 lg:pl-[92px]">
                          <SiteHeader />
                          <div id="main-content" tabIndex={-1}>
                            {children}
                          </div>
                        </div>
                        <MobileTabBar />
                        <CustomCursor />
                        <MotionPrompt />
                        <BackToTop />
                        {/* Everything loaded with `next/dynamic` + `ssr: false`
                            has to sit under a Suspense boundary once Cache
                            Components is on: a client-only component cannot be
                            prerendered, so the prerender needs somewhere to
                            stop. One boundary covers all of them — none renders
                            anything at rest, so there is nothing to fall back
                            to and `null` is the honest fallback. */}
                        <Suspense fallback={null}>
                          <LazyCommandPalette />
                          <LazyAmbientBackdrop />
                          <DeferredChrome />
                        </Suspense>
                      </SeasonalReminderProvider>
                    </TripProvider>
                  </PersonalizationProvider>
                </AuthProvider>
              </ToastProvider>
            </ViewTransitions>
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
